# Generated by Django 5.1.7 on 2025-05-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("currencies", "0002_currency_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="balance",
            field=models.DecimalField(
                decimal_places=10,
                default=0,
                help_text="Current balance in the account",
                max_digits=30,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.ForeignKey(
                help_text="Currency of the account",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="currencies.currency",
            ),
        ),
    ]
