# Generated by Django 5.1.7 on 2025-05-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        help_text="Ticker code (ISO 4217 for fiat, exchange ticker for crypto, e.g. USD, EUR, BTC, ETH)",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full currency name, e.g. 'US Dollar'", max_length=255
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Currency symbol, e.g. '$', '€'; leave null if not applicable",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        default=0,
                        help_text="Latest price relative to base currency (USD)",
                        max_digits=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Currencies",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date when this price was recorded"),
                ),
                ("price", models.DecimalField(decimal_places=12, max_digits=20)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="currency_price_date_idx")
                ],
            },
        ),
    ]
