# Generated by Django 5.1.7 on 2025-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="type",
            field=models.CharField(
                choices=[("crypto", "Cryptocurrency"), ("fiat", "Fiat currency")],
                default="crypto",
                help_text="Type of currency",
                max_length=10,
            ),
        ),
    ]
