# Generated by Django 5.1.7 on 2025-05-10 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_account_balance_account_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=10,
                        default=0,
                        help_text="Amount of the transaction",
                        max_digits=30,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account associated with the transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
