# Generated by Django 5.1.7 on 2025-05-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_remove_category_icon"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                help_text="Category of the transaction",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")], max_length=10
            ),
        ),
    ]
