# Generated by Django 5.1.7 on 2025-05-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transaction_category_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="date",
            field=models.DateField(help_text="Date of the transaction"),
        ),
    ]
