# Generated by Django 5.1.7 on 2025-05-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_balance_account_currency"),
        ("categories", "0002_remove_category_icon"),
        ("transactions", "0003_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                help_text="Account associated with the transaction",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                help_text="Category of the transaction",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="categories.category",
            ),
        ),
    ]
