# Generated by Django 5.1.7 on 2025-05-12 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_transaction_account_alter_transaction_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
